# Warnings currently triggered by your code
- ignore: {name: "Avoid lambda"} # 2 hints
- ignore: {name: "Eta reduce"} # 1 hint
- ignore: {name: "Redundant $"} # 6 hints
- ignore: {name: "Redundant as"} # 10 hints
- ignore: {name: "Redundant guard"} # 2 hints
- ignore: {name: "Redundant seq"} # 1 hint
- ignore: {name: "Unused LANGUAGE pragma"} # 3 hints
- ignore: {name: "Use :"} # 2 hints
- ignore: {name: "Use camelCase"} # 10 hints
- ignore: {name: "Use newtype instead of data"} # 4 hints
- ignore: {name: "Use unwords"} # 1 hint

# For some tests we want to write code that triggers HLint.
- ignore: {name: "Avoid reverse", within: [Lists]}
